
# Data paths
data_root: "~/quarc/data"
processed_data_root: "~/quarc/data/processed"
checkpoints_root: "~/quarc/checkpoints"
logs_root: "~/quarc/logs"

# Needed for inference
pistachio_namerxn_path: null # Required for training and inference

# Needed for preprocessing
raw_data_path: "~/quarc/data/raw"
pistachio_density_path: null # Required for preprocessing
